[package]
name = "day14"
version = "0.1.0"
authors = ["Lukasz Konopka <lukeKonopka@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
itertools = "0.9.0"
